export type ExecutionShape = 'single' | 'multiple';

export type InferExecutionShape<T> = T extends any[] ? 'multiple' : 'single';

export type ShapeOutput<T, S extends ExecutionShape> = S extends 'multiple' ? T[] : T;

/** Job execution strategy */
export enum ExecutionType {
	/** Sequential task execution */
	SEQUENTIAL = 'SEQUENTIAL',

	/** Concurrent task execution */
	PARALLEL = 'PARALLEL'
}

/** URL category for extraction and pipeline routing */
export enum ExtractionTarget {
	/** Anchor href URLs */
	ANCHORS = 'ANCHORS',

	/** Image URLs */
	IMAGES = 'IMAGES',

	/** Div href URLs */
	DIV_HREFS = 'DIV_HREFS',

	/** Media source URLs */
	SOURCES = 'SOURCES',

	/** Video poster URLs */
	VIDEO_POSTER = 'VIDEO_POSTER',

	/** All discovered URLs */
	ALL_URLS = 'ALL_URLS'
}

export enum ProviderType {
	// <auto-generated:entries>
	Beeg = 'BeegProvider',
	ColliderPorn = 'ColliderPornProvider',
	CumLouder = 'CumLouderProvider',
	Default = 'DefaultProvider',
	EPorner = 'EPornerProvider',
	HqPorn = 'HqPornProvider',
	Lesbian8 = 'Lesbian8Provider',
	MegaTube = 'MegaTubeProvider',
	MyLust = 'MyLustProvider',
	OkPorn = 'OkPornProvider',
	PerfectGirls = 'PerfectGirlsProvider',
	Porn300 = 'Porn300Provider',
	PornDoe = 'PornDoeProvider',
	PornHub = 'PornHubProvider',
	PornId = 'PornIdProvider',
	PornOne = 'PornOneProvider',
	PornsOk = 'PornsOkProvider',
	PussySpace = 'PussySpaceProvider',
	SexVid = 'SexVidProvider',
	Shameless = 'ShamelessProvider',
	SuperPorn = 'SuperPornProvider',
	SxyPorn = 'SxyPornProvider',
	TheyAreHuge = 'TheyAreHugeProvider',
	TnAFlix = 'TnAFlixProvider',
	TubeVSex = 'TubeVSexProvider',
	WallHaven = 'WallHavenProvider',
	XCafe = 'XCafeProvider',
	XGroovy = 'XGroovyProvider',
	XHamster = 'XHamsterProvider',
	XnXX = 'XnXXProvider',
	XVideos = 'XVideosProvider',
	ZzzTube = 'ZzzTubeProvider'
	// </auto-generated:entries>
}

export type UrlFormat = 'url' | 'path';

/** Video quality labels */
export enum VideoQuality {
	/** 144p quality */
	Q144 = '144p',

	/** 240p quality */
	Q240 = '240p',

	/** 360p quality */
	Q360 = '360p',

	/** 480p quality */
	Q480 = '480p',

	/** 720p quality */
	Q720 = '720p',

	/** 1080p quality */
	Q1080 = '1080p',

	/** 1440p quality */
	Q1440 = '1440p',

	/** 2160p quality */
	Q2160 = '2160p',

	/** 4320p quality */
	Q4320 = '4320p',
	/** Unknown quality */
	QUnknown = 'unknown'
}

/** Video stream formats */
export enum VideoFormat {
	/** HTTP Live Streaming */
	HLS = 'hls',

	/** MPEG-4 Part 14 */
	MP4 = 'mp4'
}

/** Video codec formats */
export enum VideoCodec {
	/** H.264 / AVC */
	H264 = 'h264',

	/** AV1 (AOMedia Video 1) */
	AV1 = 'av1'
}
