export enum MediaType {
	VIDEOS = 'videos',
	IMAGES = 'images',
	AUDIOS = 'audios',
	ALBUMS = 'albums',
	SCREENSHOT = 'screenshot',
	VIDEO_SCREENSHOT = 'video_screenshot',
	VIDEO_TIMELINES = 'video_timelines',
	VIDEO_POSTER = 'video_poster',
	ALBUM_PREVIEW = 'album_preview',
	VIDEO_ALBUM = 'video_album',
	VIDEO_PREVIEW = 'video_preview',
	THUMBNAILS = 'thumbnails',
	FAVORITES = 'favorites',
	COLLECTION = 'collection',
	UPLOADS = 'uploads',
	AVATAR = 'avatar',
	COVER = 'cover',
	CHANNELS = 'channels',
	OTHER = 'other'
}
