export type JobProgressStatus =
	| 'STARTED'
	| 'QUEUED'
	| 'DOWNLOADING'
	| 'DOWNLOADED'
	| 'COMPLETED'
	| 'FAILED'
	| 'ABORTED'
	| 'COMPLETED'
	| 'EXTRACTION-HOOK'
	| 'DOWNLOADING-HOOK';

export type ProgressDestination =
	| 'INITIALIZING'
	| 'FETCHING'
	| 'PARSING'
	| 'TRANSFORMING'
	| 'PIPELINING'
	| 'DOWNLOADING'
	| 'REQUESTING_STREAM'
	| 'HANDLING_404'
	| 'APPLYING_STRATEGY'
	| 'DETECTED_HLS'
	| 'APPLIED_HLS_QUALITY'
	| 'PARSED_DECRYPTION_HLS_KEY'
	| 'SEGMENTING-HLS'
	| 'RE_MUX_HLS'
	| 'STARTED_STREAMING';
