export enum ErrorCodes {
	INVALID_URL = 'ERR_INVALID_URL',
	SERVICE_MISMATCH = 'ERR_SERVICE_MISMATCH',
	INVALID_RANGE = 'ERR_INVALID_RANGE',
	EXTRACTION_FAILED = 'ERR_EXTRACTION_FAILED',
	DOWNLOAD_FAILED = 'ERR_DOWNLOAD_FAILED',
	UNKNOWN_ERROR = 'ERR_UNKNOWN_ERROR'
}
