import { BaseParser } from '@base';
import { ProviderType } from '@types';

type ParserCtor = new () => BaseParser;

type ParserFactory = () => Promise<ParserCtor>;

async function loadParser<T>(loader: () => Promise<Record<string, unknown>>, key: string): Promise<T> {
	const mod = await loader();

	const exported = mod[key];

	if (!exported) throw new Error(`Parser export "${key}" was not found`);

	return exported as T;
}

const parserFactories: Record<ProviderType, ParserFactory> = {
	// <auto-generated:entries>
	[ProviderType.Beeg]: () => loadParser(() => import('@provider/beeg'), 'BeegParser'),
	[ProviderType.BoKepPorn]: () => loadParser(() => import('@provider/bokepporn'), 'BoKepPornParser'),
	[ProviderType.ColliderPorn]: () => loadParser(() => import('@provider/colliderporn'), 'ColliderPornParser'),
	[ProviderType.CumLouder]: () => loadParser(() => import('@provider/cumlouder'), 'CumLouderParser'),
	[ProviderType.DaFreePorn]: () => loadParser(() => import('@provider/dafreeporn'), 'DaFreePornParser'),
	[ProviderType.DaNude]: () => loadParser(() => import('@provider/danude'), 'DaNudeParser'),
	[ProviderType.Default]: async () => BaseParser,
	[ProviderType.EpicGfs]: () => loadParser(() => import('@provider/epicgfs'), 'EpicGfsParser'),
	[ProviderType.EPorner]: () => loadParser(() => import('@provider/eporner'), 'EPornerParser'),
	[ProviderType.HqPorn]: () => loadParser(() => import('@provider/hqporn'), 'HqPornParser'),
	[ProviderType.Interracial]: () => loadParser(() => import('@provider/interracial'), 'InterracialParser'),
	[ProviderType.ItsPorn]: () => loadParser(() => import('@provider/itsporn'), 'ItsPornParser'),
	[ProviderType.Lesbian8]: () => loadParser(() => import('@provider/lesbian8'), 'Lesbian8Parser'),
	[ProviderType.MegaTube]: () => loadParser(() => import('@provider/megatube'), 'MegaTubeParser'),
	[ProviderType.MomVids]: () => loadParser(() => import('@provider/momvids'), 'MomVidsParser'),
	[ProviderType.MyLust]: () => loadParser(() => import('@provider/mylust'), 'MyLustParser'),
	[ProviderType.OkPorn]: () => loadParser(() => import('@provider/okporn'), 'OkPornParser'),
	[ProviderType.PerfectGirls]: () => loadParser(() => import('@provider/perfectgirls'), 'PerfectGirlsParser'),
	[ProviderType.Porn300]: () => loadParser(() => import('@provider/porn300'), 'Porn300Parser'),
	[ProviderType.PornDoe]: () => loadParser(() => import('@provider/porndoe'), 'PornDoeParser'),
	[ProviderType.PornHub]: () => loadParser(() => import('@provider/pornhub'), 'PornHubParser'),
	[ProviderType.PornId]: () => loadParser(() => import('@provider/pornid'), 'PornIdParser'),
	[ProviderType.PornOne]: () => loadParser(() => import('@provider/pornone'), 'PornOneParser'),
	[ProviderType.PornSeven]: () => loadParser(() => import('@provider/pornseven'), 'PornSevenParser'),
	[ProviderType.PornsOk]: () => loadParser(() => import('@provider/pornsok'), 'PornsOkParser'),
	[ProviderType.PussySpace]: () => loadParser(() => import('@provider/pussyspace'), 'PussySpaceParser'),
	[ProviderType.SexVid]: () => loadParser(() => import('@provider/sexvid'), 'SexVidParser'),
	[ProviderType.Shameless]: () => loadParser(() => import('@provider/shameless'), 'ShamelessParser'),
	[ProviderType.SuperPorn]: () => loadParser(() => import('@provider/superporn'), 'SuperPornParser'),
	[ProviderType.SxyPorn]: () => loadParser(() => import('@provider/sxyporn'), 'SxyPornParser'),
	[ProviderType.TheyAreHuge]: () => loadParser(() => import('@provider/theyarehuge'), 'TheyAreHugeParser'),
	[ProviderType.TnAFlix]: () => loadParser(() => import('@provider/tnaflix'), 'TnAFlixParser'),
	[ProviderType.TubeVSex]: () => loadParser(() => import('@provider/tubevsex'), 'TubeVSexParser'),
	[ProviderType.WallHaven]: () => loadParser(() => import('@provider/wallhaven'), 'WallHavenParser'),
	[ProviderType.XCafe]: () => loadParser(() => import('@provider/xcafe'), 'XCafeParser'),
	[ProviderType.XDegu]: () => loadParser(() => import('@provider/xdegu'), 'XDeguParser'),
	[ProviderType.XGroovy]: () => loadParser(() => import('@provider/xgroovy'), 'XGroovyParser'),
	[ProviderType.XHamster]: () => loadParser(() => import('@provider/xhamster'), 'XHamsterParser'),
	[ProviderType.XnXX]: () => loadParser(() => import('@provider/xnxx'), 'XnXXParser'),
	[ProviderType.Xozilla]: () => loadParser(() => import('@provider/xozilla'), 'XozillaParser'),
	[ProviderType.XVideos]: () => loadParser(() => import('@provider/xvideos'), 'XVideosParser'),
	[ProviderType.ZbPorn]: () => loadParser(() => import('@provider/zbporn'), 'ZbPornParser'),
	[ProviderType.ZzzTube]: () => loadParser(() => import('@provider/zzztube'), 'ZzzTubeParser')
	// </auto-generated:entries>
};

/**
 * Resolves and caches parser classes by provider.
 *
 * @remarks
 * Registries keep provider lookup out of the execution flow. They lazy-load
 * provider modules, cache constructors, and fall back to default behavior when
 * a provider-specific implementation is absent.
 */
export class ParserRegistry {
	private static readonly cache = new Map<ProviderType, ParserCtor>();

	private static async resolveParser(provider: ProviderType): Promise<ParserCtor> {
		const cached = ParserRegistry.cache.get(provider);

		if (cached) return cached;

		const factory = parserFactories[provider] ?? parserFactories[ProviderType.Default];

		const ParserClass = await factory();

		ParserRegistry.cache.set(provider, ParserClass);

		return ParserClass;
	}

	/**
	 * Creates a parser instance for the requested provider.
	 *
	 * @param provider Provider whose parser should be loaded.
	 * @returns Parser instance for the provider, or the default parser fallback.
	 */
	public static async getParser(provider: ProviderType): Promise<BaseParser> {
		const ParserClass = await this.resolveParser(provider);

		return new ParserClass();
	}
}
