import { BaseParser } from '@base';
import { Provider } from '@types';

type ParserCtor = new () => BaseParser;

type ParserFactory = () => Promise<ParserCtor>;

async function loadParser<T>(loader: () => Promise<Record<string, unknown>>, key: string): Promise<T> {
	const mod = await loader();

	const exported = mod[key];

	if (!exported) throw new Error(`Parser export "${key}" was not found`);

	return exported as T;
}

const parserFactories: Record<Provider, ParserFactory> = {
	// <auto-generated:entries>
	[Provider.AnalRz]: () => loadParser(() => import('@provider/analrz'), 'AnalRzParser'),
	[Provider.Beeg]: () => loadParser(() => import('@provider/beeg'), 'BeegParser'),
	[Provider.BlackPorn]: () => loadParser(() => import('@provider/blackporn'), 'BlackPornParser'),
	[Provider.BoKepPorn]: () => loadParser(() => import('@provider/bokepporn'), 'BoKepPornParser'),
	[Provider.ColliderPorn]: () => loadParser(() => import('@provider/colliderporn'), 'ColliderPornParser'),
	[Provider.CumLouder]: () => loadParser(() => import('@provider/cumlouder'), 'CumLouderParser'),
	[Provider.DaFreePorn]: () => loadParser(() => import('@provider/dafreeporn'), 'DaFreePornParser'),
	[Provider.DaNude]: () => loadParser(() => import('@provider/danude'), 'DaNudeParser'),
	[Provider.Default]: async () => BaseParser,
	[Provider.EpicGfs]: () => loadParser(() => import('@provider/epicgfs'), 'EpicGfsParser'),
	[Provider.EPorner]: () => loadParser(() => import('@provider/eporner'), 'EPornerParser'),
	[Provider.HqPorn]: () => loadParser(() => import('@provider/hqporn'), 'HqPornParser'),
	[Provider.Interracial]: () => loadParser(() => import('@provider/interracial'), 'InterracialParser'),
	[Provider.ItsPorn]: () => loadParser(() => import('@provider/itsporn'), 'ItsPornParser'),
	[Provider.Lesbian8]: () => loadParser(() => import('@provider/lesbian8'), 'Lesbian8Parser'),
	[Provider.MegaTube]: () => loadParser(() => import('@provider/megatube'), 'MegaTubeParser'),
	[Provider.MomVids]: () => loadParser(() => import('@provider/momvids'), 'MomVidsParser'),
	[Provider.MyLust]: () => loadParser(() => import('@provider/mylust'), 'MyLustParser'),
	[Provider.OkPorn]: () => loadParser(() => import('@provider/okporn'), 'OkPornParser'),
	[Provider.PerfectGirls]: () => loadParser(() => import('@provider/perfectgirls'), 'PerfectGirlsParser'),
	[Provider.Porn300]: () => loadParser(() => import('@provider/porn300'), 'Porn300Parser'),
	[Provider.PornDoe]: () => loadParser(() => import('@provider/porndoe'), 'PornDoeParser'),
	[Provider.PornHub]: () => loadParser(() => import('@provider/pornhub'), 'PornHubParser'),
	[Provider.PornId]: () => loadParser(() => import('@provider/pornid'), 'PornIdParser'),
	[Provider.PornOne]: () => loadParser(() => import('@provider/pornone'), 'PornOneParser'),
	[Provider.PornSeven]: () => loadParser(() => import('@provider/pornseven'), 'PornSevenParser'),
	[Provider.PornsOk]: () => loadParser(() => import('@provider/pornsok'), 'PornsOkParser'),
	[Provider.PussySpace]: () => loadParser(() => import('@provider/pussyspace'), 'PussySpaceParser'),
	[Provider.SexVid]: () => loadParser(() => import('@provider/sexvid'), 'SexVidParser'),
	[Provider.Shameless]: () => loadParser(() => import('@provider/shameless'), 'ShamelessParser'),
	[Provider.SuperPorn]: () => loadParser(() => import('@provider/superporn'), 'SuperPornParser'),
	[Provider.SxyPorn]: () => loadParser(() => import('@provider/sxyporn'), 'SxyPornParser'),
	[Provider.TheyAreHuge]: () => loadParser(() => import('@provider/theyarehuge'), 'TheyAreHugeParser'),
	[Provider.TnAFlix]: () => loadParser(() => import('@provider/tnaflix'), 'TnAFlixParser'),
	[Provider.TubeVSex]: () => loadParser(() => import('@provider/tubevsex'), 'TubeVSexParser'),
	[Provider.WallHaven]: () => loadParser(() => import('@provider/wallhaven'), 'WallHavenParser'),
	[Provider.XCafe]: () => loadParser(() => import('@provider/xcafe'), 'XCafeParser'),
	[Provider.XDegu]: () => loadParser(() => import('@provider/xdegu'), 'XDeguParser'),
	[Provider.XGroovy]: () => loadParser(() => import('@provider/xgroovy'), 'XGroovyParser'),
	[Provider.XHamster]: () => loadParser(() => import('@provider/xhamster'), 'XHamsterParser'),
	[Provider.XnXX]: () => loadParser(() => import('@provider/xnxx'), 'XnXXParser'),
	[Provider.Xozilla]: () => loadParser(() => import('@provider/xozilla'), 'XozillaParser'),
	[Provider.XVideos]: () => loadParser(() => import('@provider/xvideos'), 'XVideosParser'),
	[Provider.ZbPorn]: () => loadParser(() => import('@provider/zbporn'), 'ZbPornParser'),
	[Provider.ZzzTube]: () => loadParser(() => import('@provider/zzztube'), 'ZzzTubeParser')
	// </auto-generated:entries>
};

/**
 * Resolves and caches parser classes by provider.
 *
 * @remarks
 * Registries keep provider lookup out of the execution flow. They lazy-load
 * provider modules, cache constructors, and fall back to default behavior when
 * a provider-specific implementation is absent.
 */
export class ParserRegistry {
	private static readonly cache = new Map<Provider, ParserCtor>();

	private static async resolveParser(provider: Provider): Promise<ParserCtor> {
		const cached = ParserRegistry.cache.get(provider);

		if (cached) return cached;

		const factory = parserFactories[provider] ?? parserFactories[Provider.Default];

		const ParserClass = await factory();

		ParserRegistry.cache.set(provider, ParserClass);

		return ParserClass;
	}

	/**
	 * Creates a parser instance for the requested provider.
	 *
	 * @param provider Provider whose parser should be loaded.
	 * @returns Parser instance for the provider, or the default parser fallback.
	 */
	public static async getParser(provider: Provider): Promise<BaseParser> {
		const ParserClass = await this.resolveParser(provider);

		return new ParserClass();
	}
}
