import { BaseParser } from '@base';
import { ProviderType } from '@types';

type ParserCtor = new () => BaseParser;

type ParserFactory = () => Promise<ParserCtor>;

async function loadParser<T>(loader: () => Promise<Record<string, unknown>>, key: string): Promise<T> {
	const mod = await loader();

	const exported = mod[key];

	if (!exported) throw new Error(`Parser export "${key}" was not found`);

	return exported as T;
}

const parserFactories: Record<ProviderType, ParserFactory> = {
	// <auto-generated:entries>
	[ProviderType.Beeg]: () => loadParser(() => import('@provider/beeg'), 'BeegParser'),
	[ProviderType.ColliderPorn]: () => loadParser(() => import('@provider/colliderporn'), 'ColliderPornParser'),
	[ProviderType.Coomer]: async () => BaseParser,
	[ProviderType.CumLouder]: () => loadParser(() => import('@provider/cumlouder'), 'CumLouderParser'),
	[ProviderType.Default]: async () => BaseParser,
	[ProviderType.HqPorn]: () => loadParser(() => import('@provider/hqporn'), 'HqPornParser'),
	[ProviderType.Lesbian8]: () => loadParser(() => import('@provider/lesbian8'), 'Lesbian8Parser'),
	[ProviderType.MegaTube]: () => loadParser(() => import('@provider/megatube'), 'MegaTubeParser'),
	[ProviderType.OkPorn]: () => loadParser(() => import('@provider/okporn'), 'OkPornParser'),
	[ProviderType.PerfectGirls]: () => loadParser(() => import('@provider/perfectgirls'), 'PerfectGirlsParser'),
	[ProviderType.Porn300]: () => loadParser(() => import('@provider/porn300'), 'Porn300Parser'),
	[ProviderType.PornDoe]: () => loadParser(() => import('@provider/porndoe'), 'PornDoeParser'),
	[ProviderType.PornHub]: () => loadParser(() => import('@provider/pornhub'), 'PornHubParser'),
	[ProviderType.PornOne]: () => loadParser(() => import('@provider/pornone'), 'PornOneParser'),
	[ProviderType.PornsOk]: () => loadParser(() => import('@provider/pornsok'), 'PornsOkParser'),
	[ProviderType.PussySpace]: () => loadParser(() => import('@provider/pussyspace'), 'PussySpaceParser'),
	[ProviderType.SexVid]: () => loadParser(() => import('@provider/sexvid'), 'SexVidParser'),
	[ProviderType.Shameless]: () => loadParser(() => import('@provider/shameless'), 'ShamelessParser'),
	[ProviderType.SuperPorn]: () => loadParser(() => import('@provider/superporn'), 'SuperPornParser'),
	[ProviderType.SxyPorn]: () => loadParser(() => import('@provider/sxyporn'), 'SxyPornParser'),
	[ProviderType.TheyAreHuge]: () => loadParser(() => import('@provider/theyarehuge'), 'TheyAreHugeParser'),
	[ProviderType.TnAFlix]: () => loadParser(() => import('@provider/tnaflix'), 'TnAFlixParser'),
	[ProviderType.TubeVSex]: () => loadParser(() => import('@provider/tubevsex'), 'TubeVSexParser'),
	[ProviderType.WallHaven]: () => loadParser(() => import('@provider/wallhaven'), 'WallHavenParser'),
	[ProviderType.XGroovy]: () => loadParser(() => import('@provider/xgroovy'), 'XGroovyParser'),
	[ProviderType.XHamster]: () => loadParser(() => import('@provider/xhamster'), 'XHamsterParser'),
	[ProviderType.XnXX]: () => loadParser(() => import('@provider/xnxx'), 'XnXXParser'),
	[ProviderType.XVideos]: () => loadParser(() => import('@provider/xvideos'), 'XVideosParser')
	// </auto-generated:entries>
};

export class ParserRegistry {
	private static readonly cache = new Map<ProviderType, ParserCtor>();

	private static async resolveParser(provider: ProviderType): Promise<ParserCtor> {
		const cached = ParserRegistry.cache.get(provider);

		if (cached) return cached;

		const factory = parserFactories[provider] ?? parserFactories[ProviderType.Default];

		const ParserClass = await factory();

		ParserRegistry.cache.set(provider, ParserClass);

		return ParserClass;
	}

	public static async getParser(provider: ProviderType): Promise<BaseParser> {
		const ParserClass = await this.resolveParser(provider);

		return new ParserClass();
	}
}
