import { BasePipeline } from '@base';
import { ExecutionArgs, PipelineItem } from '@contracts';
import { FileManager } from '@storage';
import { ProviderType } from '@types';

type PipelineCtor = new (fileManager: FileManager) => BasePipeline<any, any>;

type PipelineFactory = () => Promise<PipelineCtor>;

async function loadPipeline<T>(loader: () => Promise<Record<string, unknown>>, key: string): Promise<T> {
	const mod = await loader();

	const exported = mod[key];

	if (!exported) throw new Error(`Pipeline export "${key}" was not found`);

	return exported as T;
}

const pipelineFactories: Record<ProviderType, PipelineFactory> = {
	// <auto-generated:entries>
	[ProviderType.Beeg]: () => loadPipeline(() => import('@provider/beeg'), 'BeegPipeline'),
	[ProviderType.ColliderPorn]: () => loadPipeline(() => import('@provider/colliderporn'), 'ColliderPornPipeline'),
	[ProviderType.CumLouder]: () => loadPipeline(() => import('@provider/cumlouder'), 'CumLouderPipeline'),
	[ProviderType.Default]: async () => BasePipeline,
	[ProviderType.EPorner]: () => loadPipeline(() => import('@provider/eporner'), 'EPornerPipeline'),
	[ProviderType.HqPorn]: () => loadPipeline(() => import('@provider/hqporn'), 'HqPornPipeline'),
	[ProviderType.Lesbian8]: () => loadPipeline(() => import('@provider/lesbian8'), 'Lesbian8Pipeline'),
	[ProviderType.MegaTube]: () => loadPipeline(() => import('@provider/megatube'), 'MegaTubePipeline'),
	[ProviderType.MyLust]: () => loadPipeline(() => import('@provider/mylust'), 'MyLustPipeline'),
	[ProviderType.OkPorn]: () => loadPipeline(() => import('@provider/okporn'), 'OkPornPipeline'),
	[ProviderType.PerfectGirls]: () => loadPipeline(() => import('@provider/perfectgirls'), 'PerfectGirlsPipeline'),
	[ProviderType.Porn300]: () => loadPipeline(() => import('@provider/porn300'), 'Porn300Pipeline'),
	[ProviderType.PornDoe]: () => loadPipeline(() => import('@provider/porndoe'), 'PornDoePipeline'),
	[ProviderType.PornHub]: () => loadPipeline(() => import('@provider/pornhub'), 'PornHubPipeline'),
	[ProviderType.PornId]: () => loadPipeline(() => import('@provider/pornid'), 'PornIdPipeline'),
	[ProviderType.PornOne]: () => loadPipeline(() => import('@provider/pornone'), 'PornOnePipeline'),
	[ProviderType.PornsOk]: () => loadPipeline(() => import('@provider/pornsok'), 'PornsOkPipeline'),
	[ProviderType.PussySpace]: () => loadPipeline(() => import('@provider/pussyspace'), 'PussySpacePipeline'),
	[ProviderType.SexVid]: () => loadPipeline(() => import('@provider/sexvid'), 'SexVidPipeline'),
	[ProviderType.Shameless]: () => loadPipeline(() => import('@provider/shameless'), 'ShamelessPipeline'),
	[ProviderType.SuperPorn]: () => loadPipeline(() => import('@provider/superporn'), 'SuperPornPipeline'),
	[ProviderType.SxyPorn]: () => loadPipeline(() => import('@provider/sxyporn'), 'SxyPornPipeline'),
	[ProviderType.TheyAreHuge]: () => loadPipeline(() => import('@provider/theyarehuge'), 'TheyAreHugePipeline'),
	[ProviderType.TnAFlix]: () => loadPipeline(() => import('@provider/tnaflix'), 'TnAFlixPipeline'),
	[ProviderType.TubeVSex]: () => loadPipeline(() => import('@provider/tubevsex'), 'TubeVSexPipeline'),
	[ProviderType.WallHaven]: () => loadPipeline(() => import('@provider/wallhaven'), 'WallHavenPipeline'),
	[ProviderType.XCafe]: () => loadPipeline(() => import('@provider/xcafe'), 'XCafePipeline'),
	[ProviderType.XGroovy]: () => loadPipeline(() => import('@provider/xgroovy'), 'XGroovyPipeline'),
	[ProviderType.XHamster]: () => loadPipeline(() => import('@provider/xhamster'), 'XHamsterPipeline'),
	[ProviderType.XnXX]: () => loadPipeline(() => import('@provider/xnxx'), 'XnXXPipeline'),
	[ProviderType.XVideos]: () => loadPipeline(() => import('@provider/xvideos'), 'XVideosPipeline'),
	[ProviderType.ZzzTube]: () => loadPipeline(() => import('@provider/zzztube'), 'ZzzTubePipeline')
	// </auto-generated:entries>
};

export class PipelineRegistry {
	private static readonly cache = new Map<ProviderType, PipelineCtor>();

	constructor(protected readonly fileManager: FileManager) {}

	private async resolvePipeline(provider: ProviderType): Promise<PipelineCtor> {
		const cached = PipelineRegistry.cache.get(provider);

		if (cached) return cached;

		const factory = pipelineFactories[provider] ?? pipelineFactories[ProviderType.Default];

		const PipelineClass = await factory();

		PipelineRegistry.cache.set(provider, PipelineClass);

		return PipelineClass;
	}

	public async build<TResult, TExec extends ExecutionArgs>(metadata: TResult, request: TExec): Promise<PipelineItem[]> {
		const provider = request.provider ?? ProviderType.Default;

		const PipelineClass = await this.resolvePipeline(provider);

		const pipeline = new PipelineClass(this.fileManager);

		return pipeline.build(metadata, request);
	}
}
