import { BaseStrategy } from '@base';
import { ProgressManager } from '@core/progress';
import { ProviderType } from '@types';

type StrategyCtor = new (progress: ProgressManager) => BaseStrategy;

type StrategyFactory = () => Promise<StrategyCtor>;

async function loadStrategy<T>(loader: () => Promise<Record<string, unknown>>, key: string): Promise<T> {
	const mod = await loader();

	const exported = mod[key];

	if (!exported) throw new Error(`Strategy export "${key}" was not found`);

	return exported as T;
}

const strategyFactories: Record<ProviderType, StrategyFactory> = {
	// <auto-generated:entries>
	[ProviderType.Beeg]: async () => BaseStrategy,
	[ProviderType.ColliderPorn]: async () => BaseStrategy,
	[ProviderType.Coomer]: async () => BaseStrategy,
	[ProviderType.CumLouder]: async () => BaseStrategy,
	[ProviderType.Default]: async () => BaseStrategy,
	[ProviderType.EPorner]: () => loadStrategy(() => import('@provider/eporner'), 'EPornerStrategy'),
	[ProviderType.HqPorn]: async () => BaseStrategy,
	[ProviderType.Lesbian8]: async () => BaseStrategy,
	[ProviderType.MegaTube]: async () => BaseStrategy,
	[ProviderType.MyLust]: () => loadStrategy(() => import('@provider/mylust'), 'MyLustStrategy'),
	[ProviderType.OkPorn]: async () => BaseStrategy,
	[ProviderType.PerfectGirls]: () => loadStrategy(() => import('@provider/perfectgirls'), 'PerfectGirlsStrategy'),
	[ProviderType.Porn300]: () => loadStrategy(() => import('@provider/porn300'), 'Porn300Strategy'),
	[ProviderType.PornDoe]: () => loadStrategy(() => import('@provider/porndoe'), 'PornDoeStrategy'),
	[ProviderType.PornHub]: () => loadStrategy(() => import('@provider/pornhub'), 'PornHubStrategy'),
	[ProviderType.PornId]: async () => BaseStrategy,
	[ProviderType.PornOne]: () => loadStrategy(() => import('@provider/pornone'), 'PornOneStrategy'),
	[ProviderType.PornsOk]: async () => BaseStrategy,
	[ProviderType.PussySpace]: async () => BaseStrategy,
	[ProviderType.SexVid]: async () => BaseStrategy,
	[ProviderType.Shameless]: async () => BaseStrategy,
	[ProviderType.SuperPorn]: async () => BaseStrategy,
	[ProviderType.SxyPorn]: async () => BaseStrategy,
	[ProviderType.TheyAreHuge]: async () => BaseStrategy,
	[ProviderType.TnAFlix]: async () => BaseStrategy,
	[ProviderType.TubeVSex]: async () => BaseStrategy,
	[ProviderType.WallHaven]: async () => BaseStrategy,
	[ProviderType.XCafe]: async () => BaseStrategy,
	[ProviderType.XGroovy]: () => loadStrategy(() => import('@provider/xgroovy'), 'XGroovyStrategy'),
	[ProviderType.XHamster]: () => loadStrategy(() => import('@provider/xhamster'), 'XHamsterStrategy'),
	[ProviderType.XnXX]: () => loadStrategy(() => import('@provider/xnxx'), 'XnXXStrategy'),
	[ProviderType.XVideos]: () => loadStrategy(() => import('@provider/xvideos'), 'XVideosStrategy'),
	[ProviderType.ZzzTube]: async () => BaseStrategy
	// </auto-generated:entries>
};

export class StrategyRegistry {
	private static readonly cache = new Map<ProviderType, StrategyCtor>();

	constructor(private readonly progressManager: ProgressManager) {}

	private async resolveStrategy(provider: ProviderType): Promise<StrategyCtor> {
		const cached = StrategyRegistry.cache.get(provider);

		if (cached) return cached;

		const factory = strategyFactories[provider] ?? strategyFactories[ProviderType.Default];

		const StrategyClass = await factory();

		StrategyRegistry.cache.set(provider, StrategyClass);

		return StrategyClass;
	}

	public async getStrategy(provider: ProviderType): Promise<BaseStrategy> {
		const StrategyClass = await this.resolveStrategy(provider);

		return new StrategyClass(this.progressManager);
	}
}
