import { BaseStrategy } from '@base';
import { ProgressManager } from '@core/progress';
import { Provider } from '@types';

type StrategyCtor = new (progress: ProgressManager) => BaseStrategy;

type StrategyFactory = () => Promise<StrategyCtor>;

async function loadStrategy<T>(loader: () => Promise<Record<string, unknown>>, key: string): Promise<T> {
	const mod = await loader();

	const exported = mod[key];

	if (!exported) throw new Error(`Strategy export "${key}" was not found`);

	return exported as T;
}

const strategyFactories: Record<Provider, StrategyFactory> = {
	// <auto-generated:entries>
	[Provider.AnalRz]: async () => BaseStrategy,
	[Provider.Beeg]: async () => BaseStrategy,
	[Provider.BlackPorn]: async () => BaseStrategy,
	[Provider.BoKepPorn]: async () => BaseStrategy,
	[Provider.ColliderPorn]: async () => BaseStrategy,
	[Provider.CumLouder]: async () => BaseStrategy,
	[Provider.DaFreePorn]: async () => BaseStrategy,
	[Provider.DaNude]: async () => BaseStrategy,
	[Provider.Default]: async () => BaseStrategy,
	[Provider.EpicGfs]: async () => BaseStrategy,
	[Provider.EPorner]: () => loadStrategy(() => import('@provider/eporner'), 'EPornerStrategy'),
	[Provider.HqPorn]: async () => BaseStrategy,
	[Provider.Interracial]: async () => BaseStrategy,
	[Provider.ItsPorn]: async () => BaseStrategy,
	[Provider.Lesbian8]: async () => BaseStrategy,
	[Provider.MegaTube]: async () => BaseStrategy,
	[Provider.MomVids]: async () => BaseStrategy,
	[Provider.MyLust]: () => loadStrategy(() => import('@provider/mylust'), 'MyLustStrategy'),
	[Provider.OkPorn]: async () => BaseStrategy,
	[Provider.PerfectGirls]: () => loadStrategy(() => import('@provider/perfectgirls'), 'PerfectGirlsStrategy'),
	[Provider.Porn300]: () => loadStrategy(() => import('@provider/porn300'), 'Porn300Strategy'),
	[Provider.PornDoe]: () => loadStrategy(() => import('@provider/porndoe'), 'PornDoeStrategy'),
	[Provider.PornHub]: () => loadStrategy(() => import('@provider/pornhub'), 'PornHubStrategy'),
	[Provider.PornId]: async () => BaseStrategy,
	[Provider.PornOne]: () => loadStrategy(() => import('@provider/pornone'), 'PornOneStrategy'),
	[Provider.PornSeven]: async () => BaseStrategy,
	[Provider.PornsOk]: async () => BaseStrategy,
	[Provider.PussySpace]: async () => BaseStrategy,
	[Provider.SexVid]: async () => BaseStrategy,
	[Provider.Shameless]: async () => BaseStrategy,
	[Provider.SuperPorn]: async () => BaseStrategy,
	[Provider.SxyPorn]: async () => BaseStrategy,
	[Provider.TheyAreHuge]: async () => BaseStrategy,
	[Provider.TnAFlix]: async () => BaseStrategy,
	[Provider.TubeVSex]: async () => BaseStrategy,
	[Provider.WallHaven]: async () => BaseStrategy,
	[Provider.XCafe]: async () => BaseStrategy,
	[Provider.XDegu]: async () => BaseStrategy,
	[Provider.XGroovy]: () => loadStrategy(() => import('@provider/xgroovy'), 'XGroovyStrategy'),
	[Provider.XHamster]: () => loadStrategy(() => import('@provider/xhamster'), 'XHamsterStrategy'),
	[Provider.XnXX]: () => loadStrategy(() => import('@provider/xnxx'), 'XnXXStrategy'),
	[Provider.Xozilla]: async () => BaseStrategy,
	[Provider.XVideos]: () => loadStrategy(() => import('@provider/xvideos'), 'XVideosStrategy'),
	[Provider.ZbPorn]: async () => BaseStrategy,
	[Provider.ZzzTube]: async () => BaseStrategy
	// </auto-generated:entries>
};

/**
 * Resolves provider transport strategies for HTTP clients.
 *
 * @remarks
 * The strategy registry keeps HTTP engines generic. Engines ask for the current
 * provider strategy and then apply provider-specific fallback, redirect, or
 * re-extraction behavior without importing provider modules themselves.
 */
export class StrategyRegistry {
	private static readonly cache = new Map<Provider, StrategyCtor>();

	constructor(private readonly progressManager: ProgressManager) {}

	private async resolveStrategy(provider: Provider): Promise<StrategyCtor> {
		const cached = StrategyRegistry.cache.get(provider);

		if (cached) return cached;

		const factory = strategyFactories[provider] ?? strategyFactories[Provider.Default];

		const StrategyClass = await factory();

		StrategyRegistry.cache.set(provider, StrategyClass);

		return StrategyClass;
	}

	/**
	 * Creates a strategy instance for the requested provider.
	 *
	 * @param provider Provider whose transport strategy should be loaded.
	 * @returns Provider strategy, or the default strategy fallback.
	 */
	public async getStrategy(provider: Provider): Promise<BaseStrategy> {
		const StrategyClass = await this.resolveStrategy(provider);

		return new StrategyClass(this.progressManager);
	}
}
