import { BaseTransformer } from '@base';
import { ExecutionArgs } from '@contracts';
import { ProgressManager } from '@core/progress';
import { HttpClient } from '@engine/http';
import { ProviderType } from '@types';

type TransformerCtor = new (html: HttpClient, progress: ProgressManager) => BaseTransformer<any, any>;

type TransformerFactory = () => Promise<TransformerCtor>;

async function loadTransformer<T>(loader: () => Promise<Record<string, unknown>>, key: string): Promise<T> {
	const mod = await loader();

	const exported = mod[key];

	if (!exported) throw new Error(`Transformer export "${key}" was not found`);

	return exported as T;
}

const transformerFactories: Record<ProviderType, TransformerFactory> = {
	// <auto-generated:entries>
	[ProviderType.Beeg]: () => loadTransformer(() => import('@provider/beeg'), 'BeegTransformer'),
	[ProviderType.ColliderPorn]: () => loadTransformer(() => import('@provider/colliderporn'), 'ColliderPornTransformer'),
	[ProviderType.CumLouder]: () => loadTransformer(() => import('@provider/cumlouder'), 'CumLouderTransformer'),
	[ProviderType.Default]: async () => BaseTransformer,
	[ProviderType.EPorner]: () => loadTransformer(() => import('@provider/eporner'), 'EPornerTransformer'),
	[ProviderType.HqPorn]: () => loadTransformer(() => import('@provider/hqporn'), 'HqPornTransformer'),
	[ProviderType.Lesbian8]: () => loadTransformer(() => import('@provider/lesbian8'), 'Lesbian8Transformer'),
	[ProviderType.MegaTube]: () => loadTransformer(() => import('@provider/megatube'), 'MegaTubeTransformer'),
	[ProviderType.MyLust]: () => loadTransformer(() => import('@provider/mylust'), 'MyLustTransformer'),
	[ProviderType.OkPorn]: () => loadTransformer(() => import('@provider/okporn'), 'OkPornTransformer'),
	[ProviderType.PerfectGirls]: () => loadTransformer(() => import('@provider/perfectgirls'), 'PerfectGirlsTransformer'),
	[ProviderType.Porn300]: () => loadTransformer(() => import('@provider/porn300'), 'Porn300Transformer'),
	[ProviderType.PornDoe]: () => loadTransformer(() => import('@provider/porndoe'), 'PornDoeTransformer'),
	[ProviderType.PornHub]: () => loadTransformer(() => import('@provider/pornhub'), 'PornHubTransformer'),
	[ProviderType.PornId]: () => loadTransformer(() => import('@provider/pornid'), 'PornIdTransformer'),
	[ProviderType.PornOne]: () => loadTransformer(() => import('@provider/pornone'), 'PornOneTransformer'),
	[ProviderType.PornSeven]: () => loadTransformer(() => import('@provider/pornseven'), 'PornSevenTransformer'),
	[ProviderType.PornsOk]: () => loadTransformer(() => import('@provider/pornsok'), 'PornsOkTransformer'),
	[ProviderType.PussySpace]: () => loadTransformer(() => import('@provider/pussyspace'), 'PussySpaceTransformer'),
	[ProviderType.SexVid]: () => loadTransformer(() => import('@provider/sexvid'), 'SexVidTransformer'),
	[ProviderType.Shameless]: () => loadTransformer(() => import('@provider/shameless'), 'ShamelessTransformer'),
	[ProviderType.SuperPorn]: () => loadTransformer(() => import('@provider/superporn'), 'SuperPornTransformer'),
	[ProviderType.SxyPorn]: () => loadTransformer(() => import('@provider/sxyporn'), 'SxyPornTransformer'),
	[ProviderType.TheyAreHuge]: () => loadTransformer(() => import('@provider/theyarehuge'), 'TheyAreHugeTransformer'),
	[ProviderType.TnAFlix]: () => loadTransformer(() => import('@provider/tnaflix'), 'TnAFlixTransformer'),
	[ProviderType.TubeVSex]: () => loadTransformer(() => import('@provider/tubevsex'), 'TubeVSexTransformer'),
	[ProviderType.WallHaven]: () => loadTransformer(() => import('@provider/wallhaven'), 'WallHavenTransformer'),
	[ProviderType.XCafe]: () => loadTransformer(() => import('@provider/xcafe'), 'XCafeTransformer'),
	[ProviderType.XGroovy]: () => loadTransformer(() => import('@provider/xgroovy'), 'XGroovyTransformer'),
	[ProviderType.XHamster]: () => loadTransformer(() => import('@provider/xhamster'), 'XHamsterTransformer'),
	[ProviderType.XnXX]: () => loadTransformer(() => import('@provider/xnxx'), 'XnXXTransformer'),
	[ProviderType.XVideos]: () => loadTransformer(() => import('@provider/xvideos'), 'XVideosTransformer'),
	[ProviderType.ZzzTube]: () => loadTransformer(() => import('@provider/zzztube'), 'ZzzTubeTransformer')
	// </auto-generated:entries>
};

export class TransformerRegistry {
	private static readonly cache = new Map<ProviderType, TransformerCtor>();

	constructor(
		private readonly httpClient: HttpClient,
		private readonly progressManager: ProgressManager
	) {}

	private async resolveTransformer(provider: ProviderType): Promise<TransformerCtor> {
		const cached = TransformerRegistry.cache.get(provider);

		if (cached) return cached;

		const factory = transformerFactories[provider] ?? transformerFactories[ProviderType.Default];

		const TransformerClass = await factory();

		TransformerRegistry.cache.set(provider, TransformerClass);

		return TransformerClass;
	}

	public async transform<TArgs extends ExecutionArgs, TResult>(url: string, request: TArgs): Promise<TResult> {
		const provider = request.provider ?? ProviderType.Default;

		const TransformerClass = await this.resolveTransformer(provider);

		const transformer = new TransformerClass(this.httpClient, this.progressManager);

		return (await transformer.transform(url, request)) as TResult;
	}
}
